name: hashed_kv_store
description: SHA256-based key/value store with streaming IO and multi-isolate support.
version: 0.3.0
homepage: https://github.com/fl-start/hashed_kv_store
repository: https://github.com/fl-start/hashed_kv_store
issue_tracker: https://github.com/fl-start/hashed_kv_store/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^5.0.0
